language: python

env:
  global:
    #- DEPENDS="cython>=0.19"
    - NO_NET=1

git:
  depth: 1000

matrix
  include:
    - python: 3.6
      dist: trusty
      sudo: false
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
    - python: 3.7
      dist: xenial
      sudo: true
      services:
        - xvfb
    - python: 3.8
      dist: xenial
      sudo: true
      services:
        - xvfb

install:
  - pip install numpy
  - pip install pandas
  - pip install matplotlib
  - pip install scipy
  - pip install codecov
  - pip install pytest-cov
  - pip install codacy-coverage

script:
  - py.test ./tests --cov=pyet --cov-report=xml

after_success:
   - python-codacy-coverage -r coverage.xml
