language: python

sudo: false

python:
  - 3.6

install:
  - pip install numpy
  - pip install pandas
  - pip install matplotlib
  - pip install scipy
  - pip install codecov

script:
  - cd pyet/tests
  - coverage run --source=pyeto setup.py test
